services:
  - type: web
    name: flask-backend
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:10000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.7"

  - type: static
    name: react-frontend
    buildCommand: "echo 'Frontend built!'"
    publishPath: "./frontend"